### ISSUE TITLE
linking nodes

### ISSUE THREAD

**Issue by kajvan** [productiveops/dokemon#8]
i have two servers and want one dashboard to see both. i thought you do that using the nodes but that does not really work.
is it possible?

**Comment by salilponde** [comment]
You can add nodes (servers) and when you click on the row in the table it shows the containers, images, etc. for that particular server. So using one instance of Dokemon UI you can view the containers on multiple servers.

If that is not what you are looking for, could you please explain what do you mean by one dashboard? Maybe you can jump in the Discord group to discuss - https://discord.com/invite/Nfevu4gJVG.
